
spring:
    cloud:
        stream:
            bindings:
                topicInput:
                    destination: example-exchange
                    group: queue1
            rabbit:
                bindings:
                    topicInput:
                        consumer:
                            bindQueue: true
                            bindingRoutingKey: routingKey1